********* Start testing of tst_Xunit *********
Config: Using QtTest library
PASS   : tst_Xunit::initTestCase()
WARNING: tst_Xunit::testFunc1() just a QWARN() !
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
PASS   : tst_Xunit::testFunc1()
QDEBUG : tst_Xunit::testFunc2() a qDebug() call with comment-ending stuff -->
FAIL!  : tst_Xunit::testFunc2() Compared values are not the same
   Actual   (2): 2
   Expected (3): 3
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
SKIP   : tst_Xunit::testFunc3() skipping this function!
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
FAIL!  : tst_Xunit::testFunc4() a forced failure!
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
XFAIL  : tst_Xunit::testFunc5() this failure is expected
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
PASS   : tst_Xunit::testFunc5()
XFAIL  : tst_Xunit::testFunc6() this failure is also expected
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
PASS   : tst_Xunit::testFunc6()
XPASS  : tst_Xunit::testFunc7() 'true' returned TRUE unexpectedly. ()
   Loc: [qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)]
PASS   : tst_Xunit::cleanupTestCase()
Totals: 5 passed, 3 failed, 1 skipped, 0 blacklisted, 0ms
********* Finished testing of tst_Xunit *********
