<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="13" failures="6" tests="14" name="tst_ExpectFail">
  <properties>
    <property value="@INSERT_QT_VERSION_HERE@" name="QTestVersion"/>
    <property value="@INSERT_QT_VERSION_HERE@" name="QtVersion"/>
    <property value="" name="QtBuild"/>
  </properties>
  <testcase result="pass" name="initTestCase"/>
  <testcase result="xfail" name="xfailAndContinue">
    <!-- message="begin" type="qdebug" -->
    <!-- message="This should xfail" type="info" -->
    <!-- message="after" type="qdebug" -->
  </testcase>
  <testcase result="xfail" name="xfailAndAbort">
    <!-- message="begin" type="qdebug" -->
    <!-- message="This should xfail" type="info" -->
  </testcase>
  <testcase result="fail" name="xfailTwice">
    <failure message="Already expecting a fail" result="fail"/>
  </testcase>
  <testcase result="xfail" name="xfailWithQString">
    <!-- message="A string" type="info" -->
    <!-- message="Bug 5 (The message)" type="info" -->
  </testcase>
  <testcase result="xfail" name="xfailDataDrivenWithQVerify">
    <!-- tag="Abort" message="This test should xfail" type="info" -->
    <!-- tag="Continue" message="This test should xfail" type="info" -->
  </testcase>
  <testcase result="xfail" name="xfailDataDrivenWithQCompare">
    <!-- tag="Abort" message="This test should xfail" type="info" -->
    <!-- tag="Continue" message="This test should xfail" type="info" -->
  </testcase>
  <testcase result="pass" name="xfailOnWrongRow"/>
  <testcase result="xfail" name="xfailOnAnyRow">
    <!-- tag="first row" message="This test should xfail" type="info" -->
    <!-- tag="second row" message="This test should xfail" type="info" -->
  </testcase>
  <testcase result="fail" name="xfailWithoutVerify">
    <failure tag="first row" message="QEXPECT_FAIL was called without any subsequent verification statements" result="fail"/>
    <failure tag="second row" message="QEXPECT_FAIL was called without any subsequent verification statements" result="fail"/>
  </testcase>
  <testcase result="xpass" name="xpass">
    <failure message="&apos;true&apos; returned TRUE unexpectedly. ()" result="xpass"/>
  </testcase>
  <testcase result="xpass" name="xpassDataDrivenWithQVerify">
    <failure tag="XPass" message="&apos;true&apos; returned TRUE unexpectedly. ()" result="xpass"/>
  </testcase>
  <testcase result="xpass" name="xpassDataDrivenWithQCompare">
    <failure tag="XPass" message="QCOMPARE(1, 1) returned TRUE unexpectedly." result="xpass"/>
  </testcase>
  <testcase result="pass" name="cleanupTestCase"/>
  <system-err>
<![CDATA[begin]]>
<![CDATA[This should xfail]]>
<![CDATA[after]]>
<![CDATA[begin]]>
<![CDATA[This should xfail]]>
<![CDATA[A string]]>
<![CDATA[Bug 5 (The message)]]>
<![CDATA[This test should xfail]]>
<![CDATA[This test should xfail]]>
<![CDATA[This test should xfail]]>
<![CDATA[This test should xfail]]>
<![CDATA[This test should xfail]]>
<![CDATA[This test should xfail]]>
  </system-err>
</testsuite>
